# Generated by Django 5.1.3 on 2024-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'New Order'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
